networks:
  perf:
    driver: bridge  # 定义 perf 网络
services:
  postgresql:
    image: postgres:14.5
    container_name: postgresql
    #restart: always
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - "./docker/postgresql/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - perf  # 使用 perf 网络

  frontend:
    build:
      context: ./frontend  # 指定前端项目目录
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE:-$(date +%Y%m%d_%H%M%S)}  # 添加构建参数
    container_name: frontend
    volumes:
      - "./docker/nginx/conf.d/:/etc/nginx/conf.d/"
      - "./frontend/dist/:/usr/share/nginx/html/"
    ports:
      - "8000:80"
    networks:
      - perf
    depends_on:
      - postgresql

  backend:
    build:
      context: ./mobileperf-master  # 指定后端服务目录
      dockerfile: Dockerfile  # Flask 后端服务的 Dockerfile
    volumes:
      - ./mobileperf-master/mobileperf:/app/mobileperf  # 挂载后端服务目录
    ports:
      - "5500:5500"
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgresql  # 数据库服务名称
      - PYTHONPATH=/app  # 确保 Python 能找到 /app 目录
    depends_on:
      - postgresql
    networks:
      - perf  # 使用 perf 网络
#  adb_service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: adb_service
#    volumes:
#      - .:/app
#      - ~/.android:/root/.android  # 挂载主机的 ADB key 文件
#    restart: always
#    privileged: true  # 允许容器访问 USB 设备
#    network_mode: "host"  # 使用主机网络模式
#    command: [ "adb", "-a", "nodaemon", "server" ]

  adb_services:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adb_services
    volumes:
      - .:/app
    #restart: always
    ports:
      - "5100:5100"
    privileged: true  # 允许容器访问 USB 设备
    networks:
      - perf  # 使用 Docker 网络
    #network_mode: "host"  # 使用主机网络模式
    command: [ "python3", "adb_services.py" ]

#  devices_action:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: devices_action
#    volumes:
#      - .:/app
#    #restart: always
#    ports:
#      - "5200:5200"
#    privileged: true  # 允许容器访问 USB 设备
#    networks:
#      - perf  # 使用 Docker 网络
##    logging:
##      driver: "none"
#    #network_mode: "host"  # 使用主机网络模式
#    command: [ "python3", "devices_action.py" ]